server:
  port: 8086

spring:
  application:
    name: sms-service

  # 配置RabbitMQ
  rabbitmq:
    username: leyou
    password: 
    virtual-host: /leyou
    host: 192.168.175.147

  # 配置redis
  redis:
    host: 192.168.175.147
ly:
  sms:
    apikey:  # 梦网短信网关的apiKey
    userId: # 梦网短信网关的userId
    pwd: # 梦网短信网关的password
    ipAddress1: api02.monyun.cn:7901
