server:
  port: 10010

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      serveceId: upload-service
      strip-prefix: false # 去掉前缀
  add-host-header: true # 添加host头信息
  sensitive-headers:  #

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长： 5秒

ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数，重试存在安全问题，所以不重试
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数，重试存在安全问题，所以不重试

ly:
  jwt:
    pubKeyPath: D:\ssh\id_ras.pub # 公钥地址
    cookieName: LY_TOKEN
    cookieMaxAge: 30

  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item