server:
  port: 8085

spring:
  application:
    name: user-service

  datasource:
    username: root
    password: li.13798908494
    url: jdbc:mysql://localhost:3306/yun6

  rabbitmq:
    virtual-host: /leyou
    host: 192.168.175.147
    username: leyou
    password: li.13798908494

  redis:
    host: 192.168.175.147

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    ip-address: localhost
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.leyou.user.pojo
